### ISSUE TITLE
Create a list of links to rednoise.org (relative or absolute) OUTSIDE of this repo in the project

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#104]
We will soon migrate to the new meerkat server and need to verify there are no links that will be broken after pulling to the new server. 

Note: be sure also to check in 'sketchpad/cells.json'

This should be done in some automated way, a short python 2.7 script perhaps (we may have to run it multiple times on multiple directories); it can run on local files or the web url

**Comment by cqx931** [comment]
What do you mean by ”OUTSIDE of this repo in the project“? In Miscellaneous?

Is it a recursive link checker?

**Comment by dhowe** [comment]
Anytime it links to any resource which is on rednoise, but not in the repo. All of these links will be broken if we simply clone this repo to a new server.

**Comment by cqx931** [comment]
Is this only for links that are linking from the website repo to somewhere outside the repo on rednoise? 
Like a script that goes through all the relative/absolute links and add the entry if it is not within the range of this repo?

**Comment by dhowe** [comment]
Perhaps we can use an online URL-checker if we can get it to output all the lists, but it may be difficult to figure tell which are inside and outside of the repo.

In any case, the URL is http://138.16.162.17/daniel/

**Comment by dhowe** [comment]
https://validator.w3.org/checklink?uri=http%3A%2F%2F138.16.162.17%2Fdaniel%2F&hide_type=all&recursive=on&depth=3&check=Check

**Comment by cqx931** [comment]
The whole website consists of 4 parts:
1.Projects (home and detail pages)
2.Publications
3.Reference
4.Sketch pad

Publications and Reference page doesn't have any further links and projects and sketch pad are both using dynamically created content from json. So what we need to get first is a url list from all the urls in these two json files: projects.json and cell.json. After that, we can use either url validator or python to work further on this.

**Comment by cqx931** [comment]
projects.json : all links within rednoise domain

> ../spark/
adlipo/
adverpos/
automatype/
automatype/p5/
eoe/
http://rednoise.org/daniel/pubs/the_readers_project-reading_writing_resisting-howe_cayley.pdf
http://rednoise.org/readers/hiiict.pdf
http://rednoise.org/rita/
http://rednoise.org/rita/gallery.php
http://rednoise.org/~dhowe/pubs/LEON4404_pp317-324.pdf
minordistance/
textcurtain/

**Comment by cqx931** [comment]
cells.json: all links within rednoise domain
> ../NoiseTree/
http://rednoise.org/glyphflock/
http://rednoise.org/perceptualReader/
http://rednoise.org/sketches/RasterWalk/
http://rednoise.org/sketches/Rectangles1/
http://rednoise.org/sketches/VoronoiRecode/
http://rednoise.org/~dhowe/artbots2004/htm
http://rednoise.org/~dhowe/audiomata/intro.html
http://rednoise.org/~dhowe/autocity
http://rednoise.org/~dhowe/baby
http://rednoise.org/~dhowe/blackbird
http://rednoise.org/~dhowe/bugout
http://rednoise.org/~dhowe/cellpix
http://rednoise.org/~dhowe/elmusico
http://rednoise.org/~dhowe/font3d
http://rednoise.org/~dhowe/fugue
http://rednoise.org/~dhowe/geopeep
http://rednoise.org/~dhowe/kiteworm
http://rednoise.org/~dhowe/noisemesh
http://rednoise.org/~dhowe/noteflock
http://rednoise.org/~dhowe/open.ended
http://rednoise.org/~dhowe/origami
http://rednoise.org/~dhowe/pubs.html
http://rednoise.org/~dhowe/recube
http://rednoise.org/~dhowe/stwa/showPage.html
http://rednoise.org/~dhowe/tango2
http://rednoise.org/~dhowe/text3d

**Comment by cqx931** [comment]
These links should be outside of this repo but on rednoise: 
> ../spark/
http://rednoise.org/daniel/pubs/the_readers_project-reading_writing_resisting-howe_cayley.pdf
http://rednoise.org/readers/hiiict.pdf
http://rednoise.org/rita/
http://rednoise.org/rita/gallery.php
http://rednoise.org/~dhowe/pubs/LEON4404_pp317-324.pdf

**Comment by dhowe** [comment]
I'm trying to understand the location of pdf documents linked in projects.json (some are listed above).
For each of these, please make sure that the document is included in Websites/pdfs and that it is correctly linked from the JSON (I am adding some of the raw files now)

**Comment by dhowe** [comment]
FYI: this tool works pretty-well: https://github.com/stevenvachon/broken-link-checker

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/Website/pull/114

**Comment by dhowe** [comment]
we are still missing the full 'spark' directory (a separate ticket) -- anything else?
pls. double-check, then close...

**Comment by cqx931** [comment]
`../spark/ ` is listed above in the list, it should be the last one.

**Comment by dhowe** [comment]
if that is the only one left (it has a separate ticket), then you can close this ticket...
