### ISSUE TITLE
Add automatype sketch to detail page

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#117]
http://rednoise.org/daniel/detail.html#automatype

**Comment by cqx931** [comment]
this is already added, please check the second link - "online version"

**Comment by dhowe** [comment]
actually added to the page, not a link

**Comment by cqx931** [comment]
Where? After the video as an iframe?

**Comment by dhowe** [comment]
in this case I think it should go after the image, and before the video

however, we need to figure this out for the general case, where we included a sketch on a detail page

**Comment by cqx931** [comment]
If a sketch is going to be a general case, I'm afraid the space for image/video column wouldn't be wide enough for all cases.
Also, should the sketch play automatically or start after clicking a button?

If we want an embedded sketch in the page, the place after the long introduction offers a better view.
The right column is more suitable for a preview image with pop up fancy box.

**Comment by cqx931** [comment]
@dhowe

**Comment by dhowe** [comment]
ok, agreed -- lets try the space after long-desc
note: we also need to do the same for PerceptualReader
lets try a first version that just starts playing, and then decide if its annoying

**Comment by cqx931** [comment]
First try:
https://github.com/dhowe/Website/pull/121

Automatype works quite well right now, but there is one problem for PerceptualReader using iframe: Mouse/Key event won't work inside the iframe unless the user first click the iframe.
Still need to find a workaround to solve this.
