### ISSUE TITLE
Updates to site

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#12]
1. Add Optional Large Image below text

1. Add exhibition record to all projects

1. Add links to all projects:

- RiTa
  -  RiTa on github
  -  RiTaJS on github
  -  RiTaJS on npm
  -  RiTaJS on cdnjs
- Text.curtain
  - on cover of roberto's book (http://www.transcript-verlag.de/media/image/thumbnail/9783837611304_720x720.jpg)
  - quote?
- TrackMeNot
  - paper: http://rednoise.org/pubs/TMN-Howe-Niss08-ch23.pdf
  - press? 
- AoA
  - le monde image 
- AdLiPo
  - link to Chrome store (https://chrome.google.com/webstore/detail/adlipo/pebnfdfoickfleegcnjefombjnnncpon?hl=en)
  - link to ELC entry (https://conference.eliterature.org/media/daniel-c-howe-adlipo)
  - link to ELMCIP (https://elmcip.net/creative-work/adlipo)
- Redacto
   - Chrome Store
- ChinaEye
  - 2nd image
  - add (and link) to chrome store

**Comment by cqx931** [comment]
Sorry, I just noticed this ticket today.

I have made some update mainly in the link section, but the following items are not clear:

1. Add Optional Large Image below text
Is this an optional section with one single large image or it could be several images?
I find it a bit weird in the layout to have another large image directly below the long description.
If it is going to be one single large image, I would suggest to add that below the current image.

Another option is to move the whole image section below the long description.
Exhibition record and links can go to the right column instead.

1. Add exhibition record to all projects
I have added this section in the json file, but where can I find a full exhibition record for all the projects?

1. Add links to all projects:

- Text.curtain
  - quote?
- TrackMeNot
  - press? 
- AoA
  - le monde image - what is this?
- ChinaEye
  - 2nd image - which image?(also related to the first question)

**Comment by dhowe** [comment]
> - Is this an optional section with one single large image or it could be several images?
I was thinking one optional wide image (full width of page), below both text and links on project page. Another option would be to allow multiple images in the right column, but I was really thinking about very large images, at least 3 times the width we have now...

> I have added this section in the json file, but where can I find a full exhibition record for all the projects?
I think that if I send you a current CV,  you will be able to extract entries for the various projects...


1. Add links to all projects:

> - Text.curtain
>   - quote?

Need to find a good one (can also show the book cover it was used on).
Perhaps check the reviews section I will send with CV

> - TrackMeNot
>   - press? 

Again, please try the reviews section

> - AoA
>   - le monde image - what is this?

This is an image from Le Monde newspaper (will send)

> - ChinaEye
>   - 2nd image - which image? (also related to the first question)

Screenshot from the program working (maybe it needs to be in better shape before we do this)

**Comment by dhowe** [comment]
Please also add 'Engine of Engines' (EoE) project: http://rednoise.org/eoe/

**Comment by cqx931** [comment]
https://github.com/dhowe/Website/pull/28

Optional Large Image
If you want full width images on the detail page, I would suggest to use a slider.
Or, we could use fancy box for image in bigger size and still use small thumbs for the detail page.

AoA
- I'm not sure where I should put this image yet, related to the above issue
ChinaEye
- Agreed
