### ISSUE TITLE
Previous and Next links cut off on detail pages (pr/121)

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#122]
![screen shot 2017-06-16 at 12 57 56 pm](https://user-images.githubusercontent.com/737638/27212575-82efb8f6-5293-11e7-8b16-dd973efe2a41.png)

**Comment by dhowe** [comment]
And actually we are losing a lot of page space because of the footer here. Maybe put 'next' and the project name on the same line?

**Comment by cqx931** [comment]
Or I can make the footer to use "position:fixed" only on larger screen and only shows up at the bottom of the pages. Now this happens only for screen hight smaller than 720px.

**Comment by cqx931** [comment]
close
