### ISSUE TITLE
Add mute button for automatype sketch

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#129]
also, when the video starts, the sketch should mute itself...

**Comment by dhowe** [comment]
i'll add the button

**Comment by dhowe** [comment]
and make sure the button is still visible after shrinking the canvas

**Comment by dhowe** [comment]
if easier we can use an html 'mute' link underneath, rather than a a p5.dom button

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/Website/pull/131

**Comment by dhowe** [comment]
Good, but can we make the button a bit smaller ?

**Comment by cqx931** [comment]
It's already quite small in the original sketch in my standard, do you mean making it smaller for the iframe?

**Comment by dhowe** [comment]
yes
