### ISSUE TITLE
Update AdverPos website to include Bertha 

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#136]

**Comment by cqx931** [comment]
Waiting for Leoson's final video

**Comment by cqx931** [comment]
Could you please generate one 'ad set' image for Bertha?
Ad Set for Bertha:
https://drive.google.com/file/d/0BwrY_kn-ktHENUtFUjU4ekcyZG8/view?usp=sharing

**Comment by dhowe** [comment]
http://lab-lamp.scm.cityu.edu.hk/~danihowe/ftp/Bertha-Adset.png
