### ISSUE TITLE
Automatype: auto mute sketch when not the active tab

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#141]
https://rednoise.org/daniel/detail.html#automatype

the big case is when user clicks on 'online version' to watch the large version it, but the mini-version is still playing, so it sounds/looks like everything is out of sync - so a quick fix is to perhaps to just do a mute in the onclick handler for that link... ?

**Comment by cqx931** [comment]
Please check https://github.com/dhowe/Website/pull/143

**Comment by dhowe** [comment]
strangely this fix works on chrome/firefox but not chromium

**Comment by cqx931** [comment]
Is this still valid?(It works in chromium for me)

**Comment by dhowe** [comment]
let me check
