### ISSUE TITLE
Automatype project page: add arrows & close button for large images

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#142]
I think we just need to use fancybox on the project home pages as well

------------

Should be an X at upper-right to close image (or at least clicking off the image should close it) as well as right and left arrows at edges of image to move to next or previous.

Currently the only way to navigate after opening a large image is to use the back button 

for example: https://rednoise.org/daniel/automatype/img/automatype_3.jpg

**Comment by cqx931** [comment]
fixed, please check https://github.com/dhowe/Website/pull/139
