### ISSUE TITLE
Add (good) examples screenshots page to AdLiPo website 

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#145]
lets figure out a way to show a bunch of these (see .zip below)
maybe even some sort of zoomable collage

(i have many examples, mostly from jhave):
[screens.zip](https://github.com/dhowe/Website/files/1560451/screens.zip)

**Comment by cqx931** [comment]
The easies approach would be using fancy box for image preview, and we can add another layer of image collage on top of that. It doesn't make much sense to zoom on these images as the content is not image but text, so there is always a proper image size to be able to read the image.

As for the collage, we could either use the code from adnauseam vault or other light layout library for the collage effect([Masonry](https://masonry.desandro.com/layout.html)), but with borders and margins. Something like:
![image](https://user-images.githubusercontent.com/3056154/34283575-753e3d8c-e707-11e7-91e0-21adc61af402.png)

**Comment by dhowe** [comment]
Sounds right. Though this will not change too often, so maybe ok to just manually do the collage layout?

**Comment by cqx931** [comment]
How many images do you want to include? I saw that there are images with same web page but different content, shall I just go ahead and pick one from the similar ones?

Also, is it going to be a section in the current website? (see below)

![image](https://user-images.githubusercontent.com/3056154/34285368-4f1a97d8-e714-11e7-9a85-454c4c49cfbd.png)

**Comment by dhowe** [comment]
This layout looks good.We can add a header for the collage, like "Real-world Examples"...
And as long as each image is clickable to go to full size (fancybox), then we are ok.

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/Website/pull/146
![image](https://user-images.githubusercontent.com/3056154/34288695-aead0f5e-e729-11e7-84f8-4c1092cb51f5.png)

**Comment by dhowe** [comment]
Looks good -- lets add some subtle mouse-over for the images, so that the user knows they are clickable

And lets add a subtitle below 'AdLiPo in the Wild'... 
with text: 'real-world examples, submitted by users'

**Comment by cqx931** [comment]
I didn't use all the images, only 9 out of 31 images. I don't think it looks very good for the current layout to have too many images.

**Comment by cqx931** [comment]
Where is 'AdLiPo in the Wild'? I can't find it in the current website.

**Comment by dhowe** [comment]
https://github.com/dhowe/Website/blob/master/adlipo/index.html#L404

**Comment by dhowe** [comment]
@cqx931 status?

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/Website/pull/147

**Comment by cqx931** [comment]
@dhowe Can this be closed?

**Comment by dhowe** [comment]
closed for now -- will need to update a few of the images
