### ISSUE TITLE
Fix errors on bad details page URL

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#148]
The following three ALL lead to blank pages (but instead should link back to the home page):
1. https://rednoise.org/daniel/detail.html
1. https://rednoise.org/daniel/detail.html#
1. https://rednoise.org/daniel/detail.html#badinput

The first is most crucial as this (for some unknown reason) is a live google link:

![image](https://user-images.githubusercontent.com/737638/35306281-d5c706ea-00d7-11e8-8436-1395cc3a6611.png)

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/Website/pull/149
