### ISSUE TITLE
Add 'advertising positions' to site home page

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#15]

**Comment by cqx931** [comment]
https://github.com/dhowe/Website/commit/994bd241fcff4efea6b69d26f7602cf3c48d4ddb
Still need a short introduction in the json file.

**Comment by dhowe** [comment]
Done (at least a temporary version). Perhaps we can lighten the detail image a bit?

**Comment by dhowe** [comment]
Add quotes from Dr. David Johnston:

> **Portraiture for the blemished flesh of browsing beings.**

> _Advertising Positions_ by Daniel C. Howe is a fully-articulated conceptual art intervention with an aesthetic outcome (glossy luminous and radiant rendered portraits to satisfy the narcissistic instincts of the commodified psychometric market) that at the same time operates as an engaged computationally-sophisticated (programmatic generative bot-art) and polemical intervention against the ubiquitous networked advertising that permeates and ideologically colonizes cognitive space with visual trash: portraiture for the blemished flesh of browsing beings.

**Comment by dhowe** [comment]
- Add Descriptions of each model (from wall caption-card): perhaps each model should get their own page?
- Add Wilson's blue add-collection image (zoomable)...
- Add Wall-text from the opening
- Add a couple of photos from the opening?

**Comment by cqx931** [comment]
Could you please send me all the wall-text, the blue ad-collection image in large image size and photos from Oi!'s photographer as well?

**Comment by dhowe** [comment]
First two sent, waiting on 3rd...

**Comment by dhowe** [comment]
Also, lets use the image below for the 
'Advertising Positions' detail page

![image](https://cloud.githubusercontent.com/assets/737638/21127950/c4fe03cc-c131-11e6-8230-66da25922831.png)

**Comment by cqx931** [comment]
isn't this the same with the female part of the top image?

**Comment by dhowe** [comment]
not sure, but lets use only Nicole on the details page

**Comment by cqx931** [comment]
I like the one with lighter background. What do you think?
![image](https://cloud.githubusercontent.com/assets/3056154/21144454/a322b79e-c185-11e6-9b84-227b6acadaef.png)
<hr>
![image](https://cloud.githubusercontent.com/assets/3056154/21144455/a89a5588-c185-11e6-9929-aa9c59fb0bd1.png)

**Comment by dhowe** [comment]
yes, but would also try halfway between the two grays...

**Comment by cqx931** [comment]
Please check the latest update for the adverpos website.
 
The current detail image for wilson is not very high resolution(extracted from the combined ps file), and  to be consistent it's better to use a horizontal image instead of the more square shaped one. Please check in a better detail image for wilson that you have.
