### ISSUE TITLE
Add new (Siggraph) video for Advertising Positions as link

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#157]
page: https://rednoise.org/daniel/detail.html#advertisingpositions

replace link to "Video: SIGGRAPH 2018"

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/Website/pull/160
Uploaded to vimeo

**Comment by dhowe** [comment]
not most up-to-date version

**Comment by cqx931** [comment]
updated
