### ISSUE TITLE
Add project page (and documentation) for 'Atomic Language Machines'

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#164]
Documentation banner: http://rednoise.org/ftp/alms-banner.ai, which should be cut up into individual components for the website.

**Comment by cqx931** [comment]
An mockup page to get started. Please ignore the alignment at the moment as I can't change the text much. I was imagining embedding the iframe of both versions in the webpage as what we did for Automatype. Let me know if there are any other things you want to add.
![image](https://user-images.githubusercontent.com/3056154/58374163-91da1d00-7f07-11e9-93b6-14cc57cc9fbc.png)

**Comment by dhowe** [comment]
This looks like a great start. I've now sent the text via chat.

1. I wonder if we can show the image at the top vertically (with a scroll bar), on the left or right side, next to the content.

2. How difficult would be place it on a white background ?

**Comment by cqx931** [comment]
The images are rendered on a black background, with the color scheme designed for a dark scheme. If you prefer a white background, I think re-rendering all the images for light scheme is necessary.

**Comment by cqx931** [comment]
And how about having the top image vertically as a background?
(is the Chinese version supposed to be on a blue background?)
![image](https://user-images.githubusercontent.com/3056154/58601440-b8c18780-8256-11e9-8cdc-e93eff1fde09.png)

**Comment by dhowe** [comment]
This looks really good! We can make the two 'machines' have whatever background we want (this is just what was used in the installation, but on 9 ntsc monitors.

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/Website/pull/167
Still need to make changes in the autochar folder for the resizing of the sketch in iframes.

**Comment by dhowe** [comment]
Hi Sally, this looks really good. A few minor points, which I'm sure you're aware of:

1. The text is a bit hard to read over the background image -- its not terrible, but I wonder if there is an easy way to make it better (perhaps black boxes like those on the images?)
2. autochar needs resizing and a mute button
3. pls expand the black box around the 12 decompositions, so that it has a border similar to the code box
4. 'Custom 14” NTSC monitors, bespoke software on embedded microcontrollers' should be smaller font
5. Move the 'Special thanks to Diane To.' to the very bottom

tjhanks!

**Comment by cqx931** [comment]
please check https://github.com/dhowe/Website/pull/168/commits/1ba41b83965539737fc69c3c7774314026706daf
