### ISSUE TITLE
Create separate page for Spectre project

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#166]
Can just grab this page (http://billposters.ch/spectre-launch/) from my collaborator to start, then I can do edits on text...
thanks!

**Comment by dhowe** [comment]
Some additional pages that might be useful: https://www.sheffdocfest.com/articles/778-spectre-knows?tag=alternate_realities

**Comment by cqx931** [comment]
Just added the page to start. Mostly grabbed from Bill Poster's website with artist bio from the other page. 
Cleaned it up a little bit and made a few minor changes for the design.

Once you have a better idea of the content you want to put there, I can work on a more refined design.
https://github.com/dhowe/Website/pull/168/commits/276e9367d2bbba18b282636d9fbb8040c9dd16ed
