### ISSUE TITLE
Mute automatype sketch when leaving the detailed page

### ISSUE THREAD

**Issue by cqx931** [dhowe/Website#172]
After first visiting the detailed page of automatype, if the user doesn't mute the sketch, the sketch will keep running, and it's confusing to hear the noise while browsing the projects.

**Comment by dhowe** [comment]
Yes, agreed. It should mute whenever the page loses focus. Doesn't need to automatically  unmute when users returns, but they should have the 'unmute' option

**Comment by cqx931** [comment]
fixed, please check: https://github.com/dhowe/Website/pull/173
