### ISSUE TITLE
ALMs: Higher-res background image

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#176]
Atomic Language Machines needs higher-res background image (from Dorothy's illustrator file?)

**Comment by cqx931** [comment]
I have already used the highest resolution I can get from the original illustrator file. The image itself is not in vector format in the original file(Dorothy might created the image in another file first then exported it as an image and embedded it in the final file) I can ask her for the file first.

**Comment by cqx931** [comment]
New bg image:
https://github.com/dhowe/Website/pull/185/commits/7d0c200182fead0ed75774b48ba5f54bf39eda84

**Comment by dhowe** [comment]
This looks much better, but its now a bit distracting (from the content)... 

Perhaps some combination of making it less bright or more transparent, and/or increasing the opacity of the text rectangle in front of it...

**Comment by cqx931** [comment]
Minor adjustment to the bg css is made here: https://github.com/dhowe/Website/commit/9206f20a90d7338eb643715d16c13150b52f52a8
![image](https://user-images.githubusercontent.com/3056154/62415556-b0d8e780-b5f9-11e9-971c-36a9bd55d131.png)

**Comment by dhowe** [comment]
are these changes in master?

**Comment by cqx931** [comment]
@dhowe yes

**Comment by dhowe** [comment]
mine looks like this -- is this correct?

![image](https://user-images.githubusercontent.com/737638/62415685-c7803e00-b5fb-11e9-9143-c0c0ba5aabb8.png)

**Comment by cqx931** [comment]
yes, that's also correct. It depends on the screen size. The screenshot I made was on a larger screen.
