### ISSUE TITLE
ALMS: stuck stroke

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#177]
see https://github.com/dhowe/autochar/issues/2

one struck is always stuck in vertically-oriented devices

to recreate:
1. pull dhowe/autochar
2. open index.html in a phone browser (iphone or android) OR use chrome dev tools to select any phone device

![image](https://user-images.githubusercontent.com/737638/62002573-c9ff0700-b0d4-11e9-9e22-0c654a2548c1.png)

**Comment by cqx931** [comment]
fixed, see https://github.com/dhowe/autochar/issues/2

**Comment by dhowe** [comment]
nice work!
