### ISSUE TITLE
ALMS: add more images

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#178]
![image](https://user-images.githubusercontent.com/737638/62002594-3974f680-b0d5-11e9-979c-6bb039c539a6.png)

**Comment by dhowe** [comment]
I've added a video at https://rednoise.org/ftp/ALMs.mp4.zip, which you can either use for stills or as a video

**Comment by cqx931** [comment]
I have added a video here https://github.com/dhowe/Website/pull/182/commits/549ec260767f49fbb18def7fb8e18130b5b67562
