### ISSUE TITLE
ALMs: Fix horizontal alignment of quotes

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#179]
-[x] A bit more blank vertical space at top of page (maybe double the current)
-[x] Content column should be centered
-[x] Quotations should be centered with left and right margin

![image](https://user-images.githubusercontent.com/737638/62002626-b1432100-b0d5-11e9-872a-582486410843.png)

**Comment by dhowe** [comment]
Is there a reason you changed to left-alignment for the page?

**Comment by cqx931** [comment]
@dhowe  What do you mean by "changed to left-alignment"? The image captions are now left aligned while these quotes are center aligned.

**Comment by dhowe** [comment]
The content column itself

**Comment by cqx931** [comment]
should be fixed in the latest PR
