### ISSUE TITLE
ALMs: zooming interface for horizontal banner?

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#181]
would it be possible to do a zooming interface for dorothy's horizontal banner (in high-res, linked from the project-detail page) ?

**Comment by cqx931** [comment]
waiting for #176

**Comment by dhowe** [comment]
this should be for the complet .ai file from dorothy, not the high-res bg image

**Comment by cqx931** [comment]
Added here: https://github.com/dhowe/Website/pull/185/commits/0b5f72eba9c404a63d62c0ec6515b20b70d25fe9
please check

**Comment by dhowe** [comment]
Looks good. A couple of things:
* at maximum zoom, the words are still too small to be readable (can we increase this significantly?)
* lets set the default/starting zoomed to be partially zoomed-in, something like:

![image](https://user-images.githubusercontent.com/737638/62067360-8524be80-b201-11e9-920e-371c650956ad.png)

**Comment by cqx931** [comment]
The larger text on the banner looks okay to me. Do you mean the text from the generated images(three rectangular images + the long one)?

**Comment by dhowe** [comment]
Exactly -- I'd like to be able to zoom in enough to clearly read those node-labels

**Comment by cqx931** [comment]
I need to change the image source for this since the original image contained in the current ai file is not high res enough.

**Comment by cqx931** [comment]
> lets add one or more links from the project page

What links are you referring to here?

**Comment by dhowe** [comment]
just suggesting we add a link from the 'project home page' to the zoomable interface...

**Comment by cqx931** [comment]
A link is added at the bottom of the project home page. 
https://github.com/dhowe/Website/commit/d3e168188b1db10649efb9d3e694cc1ee346da32

**Comment by dhowe** [comment]
this looks really good -- is it possible to increase the max zoom further?

**Comment by cqx931** [comment]
The max zoom and the image quality can be further improved if I try to render an image that's even larger. Right now the image is exported from AI file in 400dpi and the whole image in tiles format is already 43MB. What's the max zoom you have in mind?

**Comment by dhowe** [comment]
I think the image size is fine, but I'd like to be able to zoom in a bit more. Can we change max zoom without changing the image?

**Comment by cqx931** [comment]
Okay I see. Can you take a look at this? https://github.com/dhowe/Website/commit/f463ab11a2b6c46695b79f2199c57448eb5f6689

**Comment by dhowe** [comment]
I think this is fine, thanks!
