### ISSUE TITLE
ALMs: Add as image

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#184]
this image (or perhaps with colors inverted):

![Network-detail](https://user-images.githubusercontent.com/737638/62021232-3987fb80-b194-11e9-95e7-74e476d77130.png)

**Comment by dhowe** [comment]
![Trad-Cyto-1000_Detail](https://user-images.githubusercontent.com/737638/62021638-40177280-b196-11e9-9a8d-57ea86118d85.png)

**Comment by cqx931** [comment]
The colors look very strange after it is inverted...
![image](https://user-images.githubusercontent.com/3056154/62053728-3158ac00-b1e6-11e9-9d1b-4454843c61ed.png)

How about this:
![color](https://user-images.githubusercontent.com/3056154/62053939-9ca27e00-b1e6-11e9-81c3-dddd75ffee61.png)

**Comment by cqx931** [comment]
A better light bg version:
![Light](https://user-images.githubusercontent.com/3056154/62054258-38cc8500-b1e7-11e9-9f93-867a3f7331a0.png)

**Comment by dhowe** [comment]
Nice!

**Comment by cqx931** [comment]
It would be a bit too much to add all three images and the video to the detail page. I think either 2 images with one video or 3 images would be good.
![Screen Shot 2019-07-29 at 12 30 50 PM](https://user-images.githubusercontent.com/3056154/62065349-c9619000-b1fc-11e9-8201-f4308bbe1180.png)
![image](https://user-images.githubusercontent.com/3056154/62065607-53a9f400-b1fd-11e9-9b9d-b5a8ca1e634a.png)

**Comment by dhowe** [comment]
i dont think the video adds much, so lets remove that

**Comment by dhowe** [comment]
Lets try with the three images below, rather than what we have now:

![image](https://user-images.githubusercontent.com/737638/62415900-73775880-b5ff-11e9-99c9-7b215aeca237.png)

**Comment by cqx931** [comment]
Like this?
![Screen Shot 2019-08-03 at 3 19 55 PM](https://user-images.githubusercontent.com/3056154/62416066-67d96100-b602-11e9-89df-6f19f0c38657.png)

**Comment by dhowe** [comment]
yes, but since we don't have caption support in the template, can we add the captions (for the first two) in the image itself?

**Comment by cqx931** [comment]
Image captions within the image itself won't look very good when the images are displayed in a limited space...
I'm not sure about adding image captions into the detailed page  itself but I can add image captions to the fancy box interface if that sounds good to you.

![image](https://user-images.githubusercontent.com/3056154/62416181-d8cd4880-b603-11e9-9b17-8da2d1274ddf.png)

**Comment by dhowe** [comment]
yes, makes sense (if they are there in the JSON, otherwise as it is now)

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/Website/commit/fc9c46ac85732b6bb74c2b436a3615cc54f2b06c

**Comment by dhowe** [comment]
perfect
