### ISSUE TITLE
Advertising Positions: add missing exhibition links

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#188]
you will need to look up the correct links...

![image](https://user-images.githubusercontent.com/737638/65893332-5fbb5900-e3da-11e9-917b-9d44209a18d8.png)

**Comment by kennyviperhk** [comment]
quite strange to the second link

http://www.nabi.or.kr/page/board_view.php?brd_idx=795&brd_id=project

it will lead to bad request. quite sure the link is right. and also tested with url shortener, need to test with actual website after publish.

**Comment by dhowe** [comment]
Can you test off the cityu network?

**Comment by kennyviperhk** [comment]
yes i tried off cityu network, still the same,
<img width="465" alt="Screenshot 2019-10-14 at 3 49 55 PM" src="https://user-images.githubusercontent.com/4047303/66735907-4c0ff800-ee9a-11e9-87c9-c49d3806ac1b.png">

**Comment by dhowe** [comment]
do you get the same result if you copy/paste the url into the browser?
and does it happen with both chrome and firefox?

**Comment by kennyviperhk** [comment]
this link still bring bad request, two other links are fine

maybe becasue the link is http not https?

**Comment by kennyviperhk** [comment]
Not sure if this is the case
https://stackoverflow.com/questions/10309751/bad-request-your-browser-sent-a-request-that-this-server-could-not-understand

**Comment by dhowe** [comment]
why is this link works fine for me in both firefox and chrome ?

![image](https://user-images.githubusercontent.com/737638/76824176-49eb0480-6851-11ea-88ff-a8c336458869.png)

**Comment by dhowe** [comment]
Try this english version of the link: http://www.nabi.or.kr/en/page/board_view.php?brd_idx=795&brd_id=project

**Comment by kennyviperhk** [comment]
same bad request

**Comment by kennyviperhk** [comment]
i submit a PR and you may have a try

**Comment by dhowe** [comment]
still getting  -- mirror the site on rednoise?
![image](https://user-images.githubusercontent.com/737638/79313587-217b2680-7f33-11ea-93e1-b89db3bc211b.png)

**Comment by cqx931** [comment]
the nabi link seems to work right now, can this be closed?
