### ISSUE TITLE
Video audio does not stop when video is closed

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#189]
Problem can be seen here (open video, then close with X), but also on ALL other detail pages with video:

![image](https://user-images.githubusercontent.com/737638/65895757-8c716f80-e3de-11e9-9bb8-97048f9d6813.png)

**Comment by kennyviperhk** [comment]
fixed, pls check~

**Comment by dhowe** [comment]
is there a commit or pr ?

**Comment by kennyviperhk** [comment]
it is a commit

**Comment by dhowe** [comment]
ok, in the future leave the commit name in the comment so that I can easily check it, e.g., 616f2d99
