### ISSUE TITLE
Mute button shows in wrong position

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#193]
It is correct on the item-detail page, but not in the full-size sketch:
http://rednoise.org/autochar/index.html

![image](https://user-images.githubusercontent.com/737638/66922843-71e3fb00-f05a-11e9-9811-22266539780a.png)

![image](https://user-images.githubusercontent.com/737638/66923221-fe8eb900-f05a-11e9-9791-c1b24e53b633.png)

**Comment by cqx931** [comment]
I'm a bit confused about where the current css file for autochar is hosted. 
The webpage is currently reading from: http://rednoise.org/autochar/style.css, where the position for button is top 460 and left  630.

```
button {
  position:absolute;
  top:460px;
  left:630px;
  width:55px;
}
```

However, the css file in autochar github repo is already at the correct one(top 700, left 930). 
https://github.com/dhowe/autochar/blob/master/style.css#L8

**Comment by cqx931** [comment]
@dhowe update?

**Comment by dhowe** [comment]
this code wasn't getting update with git (fixed now)
