### ISSUE TITLE
Sketches should pause when browser tab loses focus

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#194]
sketches on the following pages should pause when browser tab loses focus:
* alms/index.html
* automatype/index.html

**Comment by kennyviperhk** [comment]
alms/index.html 1. --> fixed iframe to automatype/p5/index.html 
                               2. --> ../../autochar/index.html seems not belong to website folder. so i can't fix that.
    automatype/index.html --> did you mean detail.html#automatype ? fixed by controlling mute and unmute button

**Comment by dhowe** [comment]
please check that they restart when the user returns to the page and it has focus again

**Comment by kennyviperhk** [comment]
sketches should restart or pause then?

**Comment by dhowe** [comment]
- when user moves to another tab or window the audio should mute
- when they return to the tab with the sketch (when it gets focus again), they should unmute
- if the user ever manually mutes the sketch, then it should remain muted, regardless of focus

**Comment by dhowe** [comment]
status?

**Comment by kennyviperhk** [comment]
-able to mute and unmute the sketch while away and back
- tried a couple of time, since the mute button is inside the iframe, i can't trace if the mute button is previously pressed or not.

**Comment by dhowe** [comment]
Doesn't matter what happens when the user returns to the page, but it needs to:
1. Mute when user leaves the page or focuses on a different tab or app
2. Stay muted if the user mutes

**Comment by kennyviperhk** [comment]
since the mute button is inside the iframe, i can't trace if the mute button is previously pressed or not. -> cannot trace 2.Stay muted if the user mutes

**Comment by dhowe** [comment]
> since the mute button is inside the iframe, i can't trace if the mute button is previously pressed or not. -> cannot trace 2.Stay muted if the user mutes


don't need to trace, just mute when the user leaves the leaves the page or focuses on a different tab or app

**Comment by kennyviperhk** [comment]
yes now works, but it will unmute anyway when come back
