### ISSUE TITLE
Check/fix broken gallery pages

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#198]
2. Cornels Yoke doesn't work 
1. Memoire has no sound

check the rest...

**Comment by kennyviperhk** [comment]
- Mirroring Tears: Visages by John Cayley Penny Florence - their whole site is down:

503 Service Temporarily Unavailable
keep or remove?

- Cornels Yoke - fixed

- Memoire has no sound - not sure how to fix yet....

- #nightTweets - removed as last time mentioned (also in web version 2)

this issues are RiTa git..

**Comment by dhowe** [comment]
cool -- important to sound on 'memoire', even it involves a dialog box asking the user if sound is ok 
I will ask cayley about 'Mirroring Tears'

see also tickets for new gallery projects

**Comment by kennyviperhk** [comment]
'Mirroring Tears' is up on the elmcip, which is fine for now: https://elmcip.net/creative-work/mirroring-tears-visages
Done

just tested Memoire again,
Chrome is blocking audio of http (https://www.engadget.com/2019/10/04/chrome-security-block-http-content/), firefox has to manually allow audio (did not pop up) 

i have changed to the download version of it for now.
http://collection.eliterature.org/2/works/soderman_memory.html

**Comment by dhowe** [comment]
if Mirroring Tears is has been updated, then this can be closed. I am creating a new ticket for 'Memoire'
