### ISSUE TITLE
Update Spectre with awards. etc

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#202]
from this page: http://billposters.ch/blog-news/

**Comment by dhowe** [comment]
We need to add (postponed) to the Austin and Rochester shows. 
Also Havana, Cuba is not listed here -- should also be marked as (postponed)

**Comment by dhowe** [comment]
Status?

**Comment by dhowe** [comment]
Great. If you could make one final tweak by adding a blank line at the bottom of the page, then this can be closed.

![image](https://user-images.githubusercontent.com/737638/88089017-eb96af80-cbbd-11ea-8b1e-a1f9e559b01f.png)

**Comment by cqx931** [comment]
That parts looks okay on my side.
<img width="1243" alt="Screenshot 2020-07-21 at 7 06 40 PM" src="https://user-images.githubusercontent.com/3056154/88115914-511a7a00-cb85-11ea-8a66-2ca46c05d94c.png">

I have added a bit more bottom margin for content, let me know if that fixes the problem for you.
https://github.com/dhowe/Website/commit/a21ab3fa1699cbf886b01c0a2767f54e21c96d02

**Comment by cqx931** [comment]
can this be
