### ISSUE TITLE
Website Update

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#204]
Primary change are to homepage:
1. Show only images in a grid similar to [this](http://www.paglen.com/?l=work), though wider (either 1-2-1 or 1-2-1-2 arrangement). 
1. Show title/text only on hover as in above link
1. Design/integrate news blog as discussed, with data like [this](http://billposters.ch/blog-news/)

Work on this in a separate branch (1. should probably collapse to fewer columns for responsive/mobile view)

**Comment by dhowe** [comment]
Also, fix white border on sketch:

![image](https://user-images.githubusercontent.com/737638/79629709-4a432c00-817e-11ea-921a-414b2be9da44.png)

**Comment by dhowe** [comment]
The home page looks pretty good, though the large images seem too large -- did you try any of the arrangements I suggested above? Can you try some quick paper/pencil sketches of different layouts?
Also we need to make sure that we have large enough images for the big images so that they aren’t pixelated.

Lets put building the blog page on hold until we have an agreed upon design for how it will fit into the site...

**Comment by dhowe** [comment]
In order to simplify, lets do it like this:
Note that the content should center, as it is now) but the left edge should not move beyond the left edge of the 'PROJECTS' text at top (see the red line)
![website-sketch](https://user-images.githubusercontent.com/737638/80412997-4b542600-8901-11ea-90d2-540317ab14d4.png)

**Comment by kennyviperhk** [comment]
it makes more sense to fix the alignment upon to the projects button, as the footer also aligned this way. please check.

**Comment by dhowe** [comment]
Questions:
- [ ] Headers disappear when window is narrow
- [ ] Text is unreadable over some images
- [ ] Cannot scroll to bottom most images

**Comment by kennyviperhk** [comment]
Headers is hidden as clickable menubar as it is in previous design, so it is not an issue unless u want to change it.

**Comment by dhowe** [comment]
> Headers is hidden as clickable menubar as it is in previous design, so it is not an issue unless u want to change it.

Visitors need to be able to see the menu options --  where is the clickable menubar? 

![image](https://user-images.githubusercontent.com/737638/81276575-c649d900-9085-11ea-81e7-f248ff9f317f.png)

**Comment by kennyviperhk** [comment]
Your name is the button now, suggest to change to a button on the right like rita new website

**Comment by dhowe** [comment]
agreed

**Comment by dhowe** [comment]
menu looks good, 2nd checkbox still pending
- [x] change mobile menu button from name to right-side menu (like new RiTa website)
- [ ] reduce size of all images on homepage by 75%

**Comment by dhowe** [comment]
The aspect ration, on a larger screen, should look like this:

![image](https://user-images.githubusercontent.com/737638/82746010-94db4800-9dbd-11ea-9f45-65c98f4014e0.png)
