### ISSUE TITLE
Aspect ratio incorrect for images at some widths

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#214]
If you expand the page greater than 1100px then it looks OK (1st img)
If less than 1100px, you can see that the image aspect ratio is wrong (2nd img)
The code is, I believe in [css/main.css](https://github.com/dhowe/Website/blob/master/css/main.css#L710)

![image](https://user-images.githubusercontent.com/737638/83428338-c8c10800-a464-11ea-988f-dec594b67360.png)
![Screenshot 2020-06-02 at 12 04 33 AM](https://user-images.githubusercontent.com/737638/83428342-ca8acb80-a464-11ea-9dfb-2d6b90c8969b.png)

**Comment by cqx931** [comment]
The aspect ratio is correct, the image was cutter to fit into space. Though the image height should be larger for the second screenshot.
I can fix it to this(see that image still has to be cutter to fit into the current grid design)
<img width="702" alt="Screenshot 2020-06-02 at 1 46 34 PM" src="https://user-images.githubusercontent.com/3056154/83552272-7b31b300-a4d7-11ea-9109-c46afbea2aac.png">

**Comment by dhowe** [comment]
that looks good

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/Website/commit/b236350f177b29955f7e111990a04b7cefa48a4e

**Comment by dhowe** [comment]
question: why does the image height have to change when the width of the window is adjusted?

**Comment by cqx931** [comment]
fixed
