### ISSUE TITLE
About page (mobile) needs better layout

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#215]
![Screenshot 2020-06-03 at 4 06 55 AM](https://user-images.githubusercontent.com/737638/83564738-cedfe300-a54f-11ea-956f-11d0f4d9f9fe.png)

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/Website/pull/222/commits/3fd7913770abee071e64f598444caf6bf6e23f55
