### ISSUE TITLE
Add events in lefthand column for desktop view

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#220]
Something like this, but on the left:

![image](https://user-images.githubusercontent.com/737638/84100675-f26ac800-aa3e-11ea-8e7d-b2883958de23.png)

**Comment by dhowe** [comment]
lets discuss

**Comment by cqx931** [comment]
![image](https://user-images.githubusercontent.com/3056154/88052115-bfc8ea80-cb27-11ea-9ebd-9ed153afb119.png)

**Comment by cqx931** [comment]
For the word press site, I referred to [this post](https://medium.com/@dalenguyen/how-to-get-featured-image-from-wordpress-rest-api-5e023b9896c6) to import featured images.

**Comment by dhowe** [comment]
This looks really great!

One thing I notice is that Its not 100% clear that the events are clickable...Can we add a mouse-over for each so that the background color perhaps turns light-gray on hove (as we used to have for the projects) ?

**Comment by cqx931** [comment]
<img width="588" alt="Screenshot 2020-07-24 at 8 43 56 AM" src="https://user-images.githubusercontent.com/3056154/88392346-d1a9c800-cd89-11ea-9c59-e69f4c09a70e.png">
I don't see such a big gap when I check the events locally on my side.

**Comment by dhowe** [comment]
- [ ] events do not resize when window height changes (should show different # of events)
- [ ] make name, events header and events left-align (see below)

![image](https://user-images.githubusercontent.com/737638/88421744-a8397c80-ce1b-11ea-875f-67ad0539ebcd.png)

**Comment by cqx931** [comment]
please check: https://github.com/dhowe/Website/commit/749f1c9b338d8171cb3ac5df03ce9d90c35c3d0c

**Comment by dhowe** [comment]
looks great, thanks

**Comment by cqx931** [comment]
done
