### ISSUE TITLE
Ready new design to go live

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#221]
lets get the new website design pushed live:
- [x] check resolution of all images and replace any pixelated/low-res
- [x] check display in all mobile

**Comment by cqx931** [comment]
Do we have better images for the following projects?

Project page: 

- [ ] AdLiPo

- [ ] All your google are belong to us

- [ ] Open Ended

**Comment by dhowe** [comment]
No. I can try _to_ find one for open.ended. Perhaps we can create new ones for the other two? Starting with:
* All your google: https://i.ytimg.com/vi/Um0TLiWa8Dw/maxresdefault.jpg
* AdLiPo:

**Comment by cqx931** [comment]
Like this?
<img width="565" alt="Screenshot 2020-07-07 at 7 56 26 AM" src="https://user-images.githubusercontent.com/3056154/86777610-5e812180-c027-11ea-87d5-9fd50e8dbd90.png">

**Comment by dhowe** [comment]
yes, looks better

**Comment by cqx931** [comment]
Could do two more feature projects, how about these two?
<img width="897" alt="Screenshot 2020-07-07 at 8 37 03 AM" src="https://user-images.githubusercontent.com/3056154/86782434-0baa6880-c02d-11ea-8029-3c84b6662a06.png">

**Comment by cqx931** [comment]
Automatype should also looks nice with larger feature image

**Comment by dhowe** [comment]
was thinking also: 
* adnauseam
* how it is
* automatype
* radical of the vertical
* readers project

probably not 'dialogic'

**Comment by cqx931** [comment]
Yes it's pretty easy to add them, but layout wise I think it's better if there are not too many featured projects.

**Comment by dhowe** [comment]
there should always be exactly 2, but randomly selected from the list (above)

**Comment by cqx931** [comment]
ah okay, I see that makes more sense.

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/Website/pull/226

**Comment by dhowe** [comment]
A couple more issues:

- [ ] Resolution still looks too low (can shrink images and/or up-res photos) 
- [ ] Featured randomization doesn't select all project 
- [ ] Intermittent error on retinajs (see below)

![image](https://user-images.githubusercontent.com/737638/87849949-14e5e000-c91f-11ea-9173-9081efc4fcb7.png)

**Comment by cqx931** [comment]
> Is it possible to cutoff the text (and add ellipses) before the last line of each desc ?

You are talking about the short descriptions for the main page right?

**Comment by dhowe** [comment]
Yes. Do circled in the image below

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/Website/pull/228
I can't find images for How It Is in better resolutions, could you try to find some? Both for the main page and the detail page.

**Comment by dhowe** [comment]
Which image are you referring to on the detail page?

![Screenshot 2020-07-19 at 1 19 29 PM](https://user-images.githubusercontent.com/737638/87867723-85920880-c9c2-11ea-888b-652bca60c4a1.png)

**Comment by dhowe** [comment]
I'm still seeing the retina error in chrome:

![image](https://user-images.githubusercontent.com/737638/87867969-6dbb8400-c9c4-11ea-8c45-378a3e5a1977.png)

**Comment by cqx931** [comment]
The proj/normalize.css file has only been used in the selected project page(proj.html), isn't that what you have created back then? If the selected project page is no longer needed, we can remove proj.html and the corresponding css folder

**Comment by cqx931** [comment]
As for the retina error, have you tried clearing the browsing data? I can no longer see the error on my side.
<img width="840" alt="Screenshot 2020-07-20 at 10 46 23 AM" src="https://user-images.githubusercontent.com/3056154/87951187-432a0380-ca76-11ea-84ef-21b0ea76a218.png">

**Comment by dhowe** [comment]
I see it only on localhost

**Comment by dhowe** [comment]
but yes, you can remove proj.html and the 2nd normalize

**Comment by dhowe** [comment]
but you can see pixels in the featured images, for example:

![image](https://user-images.githubusercontent.com/737638/87954247-a9e30780-cade-11ea-96ea-2533716896c9.png)

**Comment by dhowe** [comment]
![image](https://user-images.githubusercontent.com/737638/87954582-237af580-cadf-11ea-94ca-eb1d25ba9ec6.png)

**Comment by cqx931** [comment]
Featured projects should now use @2x images by default.
Please check https://github.com/dhowe/Website/pull/231
