### ISSUE TITLE
Add header to blog pages

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#235]
Is this possible/easy? Problem is that once someone ends up on a blog page there is no way to get back to the main site

**Comment by cqx931** [comment]
Isn't it already added?
<img width="1194" alt="Screenshot 2020-07-27 at 8 53 00 AM" src="https://user-images.githubusercontent.com/3056154/88543864-948e4180-cfe6-11ea-90b8-dd0f146310d6.png">

**Comment by dhowe** [comment]
the actual post page (if you click on one of the items above)

**Comment by cqx931** [comment]
I see

**Comment by cqx931** [comment]
Added header to both blog pages and search result pages
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/3056154/88545965-b210da80-cfe9-11ea-822b-76bad7e1817d.png">
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/3056154/88545976-b50bcb00-cfe9-11ea-882c-f8c8d748c1ee.png">
