### ISSUE TITLE
Problem with scrolling on homepage

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#237]
Cannot scroll below the following level:

![image](https://user-images.githubusercontent.com/737638/88562761-ad890800-d063-11ea-81c3-9bbe79a8a703.png)

**Comment by cqx931** [comment]
See: https://github.com/dhowe/Website

**Comment by dhowe** [comment]
this looks good, but can we add a slightly bigger margin after the last row of projects, so that one knows there are no more?

**Comment by cqx931** [comment]
Seems like an issue with large screens, fixed here: https://github.com/dhowe/Website/commit/2198509bea9dbf5ac827c4af3a5164cc69e321d4

**Comment by dhowe** [comment]
looks good, but see #239
