### ISSUE TITLE
Problem with scrolling and images

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#239]
see lower right corner

![image](https://user-images.githubusercontent.com/737638/88693860-6289f600-d132-11ea-8748-3715b798bfc7.png)

**Comment by cqx931** [comment]
Could you provide more details on how to reproduce this issue?

**Comment by dhowe** [comment]
Open chrome to [the page](https://rednoise.org/daniel/detail.html#radicaloftheverticalheart) using a tall window. Grab the bottom right corner and drag upward, decreasing the window height until the bottom-most image is blocked behind the previous-next button bar

**Comment by dhowe** [comment]
👍
