### ISSUE TITLE
Featured AdNauseam image is not clickable (FF)

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#240]
A strange one: when ADN is a featured project (lg image) only the title is clickable, not the image itself...
I am guessing it is bc of the hrefs in the text (see projects.json)

![image](https://user-images.githubusercontent.com/737638/88763005-eed50100-d1a4-11ea-9201-c09d04b8d840.png)

**Comment by cqx931** [comment]
varified

**Comment by cqx931** [comment]
In general, I think links within short description don't work well with the current design. 
@dhowe Can we move the two links to long descriptions? (can be placed after the first sentence)
-> They are for "(banned by Google and recommended by Mozilla)"
<a href=\"https://addons.mozilla.org/en-US/firefox/addon/adnauseam/\" target=\"_new\”>
<a href=\"https://www.fastcompany.com/3068920/google-adnauseam-ad-blocking-war\" target=\"_new\">

**Comment by dhowe** [comment]
yes, sure

**Comment by cqx931** [comment]
Done https://github.com/dhowe/Website/commit/f5b0aff1c0ac38206a59fbc5a0dc94ae19b822db
