### ISSUE TITLE
[rewire] Re-add EOE videos to project home page

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#245]
Currently works only intermittently, needs css at least ...

Can add very thin white border around video

FILE: /pages/eoe/index.html
VIDEO: 

```
<source src="../../res/video/eoe.mp4" type="video/mp4">
<source src="../../res/video/eoe.webm" type="video/webm">
```
![image](https://user-images.githubusercontent.com/737638/88888556-1b564f00-d271-11ea-9160-29ea1792b451.png)

**Comment by cqx931** [comment]
Is it also related to this setting in Firefox?
<img width="417" alt="image" src="https://user-images.githubusercontent.com/3056154/88936580-0ec1fe80-d251-11ea-8772-536e32d51f5a.png">

**Comment by cqx931** [comment]
See: https://github.com/dhowe/Website/commit/9aac21c42669e36d2fc57140021d01b264b75d1a
