### ISSUE TITLE
Audio not playing on Minor Distance page

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#247]
Errors in console

PAGE: /pages/minordistance/index.html

![Screenshot 2020-07-30 at 2 54 49 PM](https://user-images.githubusercontent.com/737638/88890743-a38a2380-d274-11ea-9021-bd33b7cc3bda.png)

**Comment by cqx931** [comment]
What error message do you see? 
I can get audio playing without issues, both in firefox and chrome.

<img width="573" alt="image" src="https://user-images.githubusercontent.com/3056154/88924764-b0d9ea80-d241-11ea-92d3-c0c4cf693226.png">

**Comment by dhowe** [comment]
sees fine now
