### ISSUE TITLE
Run link-checker on new website org to find any broken

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#249]

**Comment by cqx931** [comment]
The readers:
http://thereadersproject.org/index.php?p=installation/HK2014/wmc.html
adnauseam:
https://www.english.printscreenfestival.com/into-the-deep
adlipo:
https://conference.eliterature.org/media/daniel-c-howe-adlipo
trackmenot:
http://www.motimuseum.nl/en/tentoonstelling/design-myprivacy/
readforus: (temporary)
https://www.brown.edu/campus-life/arts/bellgallery/exhibitions/faculty-triennial-exhibition-2010

pdf path errors fixed here:
https://github.com/dhowe/Website/commit/f137efc2e1add5810611c575502ee9dd2782f43a

**Comment by dhowe** [comment]
[ ] 'Into the Deep': Lets create a blog post from [this page](https://www.midnighteast.com/mag/?p=49140) then link to it

**Comment by cqx931** [comment]
The two posts can be found at:
https://rednoise.org/wpr/2018/10/15/print-screen-2018-fake-it-make-it/
https://rednoise.org/wpr/2016/05/27/design-my-privacy/

links fixed here:https://github.com/dhowe/Website/commit/68f1a6979a0f5ca629e8094a3fe4d5f0c398fc62
