### ISSUE TITLE
AdverPos: Increase size of animations

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#25]
If they are going to be on their own page, then I think the animations needs to be larger, about 600 pixels wide

**Comment by cqx931** [comment]
I see, the video is in 640 x 320, though I the current quality doesn't looks very nice when it is that big. I will render one with higher quality with the same size.

**Comment by cqx931** [comment]
done https://github.com/dhowe/Website/pull/28/commits/728bbe6bdd546886ec8ca76d49a8ee5afe838b56
