### ISSUE TITLE
Delay of css loading in wordpress

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#258]
Page (https://rednoise.org/wpr/) loads first without css, only later correctly:

![image](https://user-images.githubusercontent.com/737638/94951415-ceb01e00-0516-11eb-94a6-c69508a421d1.png)

**Comment by cqx931** [comment]
This is fixed now. (might need to clear cache first)

Seems to be mostly related to the position where I put the headers html in the index.php page. But there is also people saying additional css styles are rather slow to load. So I modified both and it looks good now.

**Comment by dhowe** [comment]
great, thanks so much @cqx931 !
