### ISSUE TITLE
AdverPos: Indicate which page user is on in navigation

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#26]
Website/adverpos/nicole.html
Website/adverpos/wilson

![screen shot 2016-12-14 at 9 20 02 pm](https://cloud.githubusercontent.com/assets/737638/21183501/3119c638-c243-11e6-9d92-3007eb3d720a.png)

**Comment by cqx931** [comment]
done https://github.com/dhowe/Website/pull/28/commits/728bbe6bdd546886ec8ca76d49a8ee5afe838b56
