### ISSUE TITLE
Post-exhibitions checking

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#30]
- [x] use Nicole's ads for blue collection image on [this page](http://localhost/Documents/Projects/Website/adverpos/index.html)
- [x] download external resources so we have a local copy (EoE brochure, for example)
- [x]  make detail image into array of fancybox-able images (adjust json + html code)
- [x] adjust vertical spacing of exhibition list 
- [x] add 'Projects made with RiTa' (Roulette, Readers, HIIIiCT, Automatype, AoA, Text.curtain, AdLipo, NoTimeMachine: http://archive.turbulence.org/Works/notime/about.html, open.ended: http://collection.eliterature.org/1/works/howe_kaprinska__open_ended.html)
- [x] set max-width for all text-blocks so that we have 12 words per line or less (on average)
- [x] new RiTa small image (match with the large one)
- [x] AoA exhibitions appear to be replaced with those for Minor Distance 
- [x] quotation text (not the author) should be italic
- [x] under exhibitions for Readers, add this link: http://thereadersproject.org/outcomes.html#CV
- [x] proper formatting of exhibitions (like CV, use italics, etc.)
- [x] remove grey area on left of adverpos website
- [x] left-align footer with context-text on pubs/refs.html (or alternatively, center-align the content)
- [x] add subtle grey border to redacto small image (redacto_s.png)
- [x] consistency in link color between exhibitions and links
- [x] convert videos to proper format (and add one for each, or ask me if not sure)

**Comment by dhowe** [comment]
is there a reason why we are missing some @2x images (on index.html, for example)?

**Comment by cqx931** [comment]
up to this point, all the large images have @2x images. The missing ones are small images for index.html, as we don't have that particular image in better resolution. We could change to other images we have for the same project.
Missing list:
adlipo, the readers project, redacto,roulette.

**Comment by cqx931** [comment]
> proper formatting of exhibitions (like CV, use italics, etc.)
Italics are mainly used for the name of the work in the CV, are we going to include the name of the work in the webiste? If not, I only see "Drunkden boat" and "Theoretical Architecture" that uses Italics.

**Comment by dhowe** [comment]
Just names of shows, e.g., "Montage Express"...

**Comment by cqx931** [comment]
close
