### ISSUE TITLE
Check HTML/CSS validity

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#4]
@cqx931 please fix the errors [here] (https://validator.w3.org/) and [here](http://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2F138.16.162.17%2F~dhowe)

**Comment by cqx931** [comment]
got a "404 not Found" in the first link:
https://validator.w3.org/checkuri=http%3A%2F%2F138.16.162.17%2F~dhowe

**Comment by cqx931** [comment]
[html validator for the entire site](http://www.htmlhelp.com/cgi-bin/validate.cgi?url=http%3A%2F%2F138.16.162.17%2F~dhowe&warnings=yes&spider=yes&hidevalid=yes)

**Comment by cqx931** [comment]
fixed

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/Website/pull/7
