### ISSUE TITLE
Text box disappears on adverpos->adset page

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#54]
![screen shot 2016-12-28 at 1 02 23 am](https://cloud.githubusercontent.com/assets/737638/21504392/85aba56c-cc99-11e6-85ce-bbccb1210ad1.png)

**Comment by cqx931** [comment]
accidentally pushed the code for gallery zoom. will push it later when it is ready.
https://github.com/dhowe/Website/pull/55
