### ISSUE TITLE
AdverPos: zooming problem

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#58]
this happens on click: top half is zoomable, bottom appears to be the older, low-res image... (otherwise zooming looks quite nice)

![screen shot 2016-12-29 at 11 49 11 pm](https://cloud.githubusercontent.com/assets/737638/21547990/55a40ef4-ce24-11e6-8061-238be5d7173f.png)

**Comment by cqx931** [comment]
https://github.com/dhowe/Website/pull/62 fixed
