### ISSUE TITLE
AdverPos: lighting too dark on animations

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#59]
Wonder if there is anything we can do about this short of re-rendering?

**Comment by cqx931** [comment]
I think so... A lighter background can also improve this issue.

**Comment by dhowe** [comment]
@cqx931 is this something we can do in the short-term, without re-rendering (perhaps in after-effects or premiere) ?

**Comment by cqx931** [comment]
We definitely can improve the lighting without re-rendering. Maybe Dorothy can try to improve the lighting with video editing first, and see how good we can do without re-rendering.

**Comment by dhowe** [comment]
Sounds good, pls mention to her...

**Comment by dhowe** [comment]
@cqx93, I think we're ready to upload to site

**Comment by cqx931** [comment]
close
