### ISSUE TITLE
Run link-checker on site

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#6]
https://validator.w3.org/checklink?uri=http%3A%2F%2F138.16.162.17%2F~dhowe%2F&hide_type=all&recursive=on&depth=2&check=Check#results4

@cqx931 please fix whichever of these you can, and otherwise add to the ticket below...

**Comment by cqx931** [comment]
The following links are missing for publication page:
http://138.16.162.17/~dhowe/pubs.html

![screen shot 2016-09-09 at 1 15 44 pm](https://cloud.githubusercontent.com/assets/3056154/18376220/aa287b32-768f-11e6-9b8b-605991122f87.png)

**Comment by cqx931** [comment]
footer --> My GPG Key
This was the way it opens the link in your current personal website, shall I change it to a non-javascript link or you want to keep it?
![screen shot 2016-09-09 at 1 18 53 pm](https://cloud.githubusercontent.com/assets/3056154/18376251/fcfa6dd4-768f-11e6-8489-1b46ac628333.png)

**Comment by dhowe** [comment]
Sure --  it should open a new tab/window

**Comment by cqx931** [comment]
-change the redirected link
-manually check the links that are forbidden by robot.txt

**Comment by cqx931** [comment]
done
