### ISSUE TITLE
AdverPos: image alignment 

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#63]
I made some minor changes to the images on the index page, however the horizontal alignment is not quite correct:

![screen shot 2017-01-03 at 1 28 48 am](https://cloud.githubusercontent.com/assets/737638/21593620/177909f8-d154-11e6-9428-b5b36e98b5a6.png)

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/Website/pull/65/commits/89c0bfafe823345e8e3cd7f7fea582c482d27688
