### ISSUE TITLE
Pixelation on Wilson's head

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#64]
![screen shot 2017-01-03 at 1 27 53 pm](https://cloud.githubusercontent.com/assets/737638/21600523/a5917716-d1b8-11e6-9ae2-27677bd43cec.png)

**Comment by cqx931** [comment]
updated better images for all the top images
https://github.com/dhowe/Website/pull/65/commits/1e14f12062e78049056e08c366aeb37055cf1397
