### ISSUE TITLE
Videos don't play in Chromium

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#71]
Though fine in Google Chrome.

Chromium: Version 55.0.2883.95 (64-bit), on OSX 10.10.5

![screen shot 2017-01-17 at 8 18 15 pm](https://cloud.githubusercontent.com/assets/737638/22020232/23915bec-dcf2-11e6-8918-6147a645fc86.png)

**Comment by cqx931** [comment]
This should be a fancy box issue. Html5 videos work fine on adverpos site http://rednoise.org/dhowe/adverpos/nicole.html

**Comment by dhowe** [comment]
ok, good -- but still need to fix it

**Comment by cqx931** [comment]
https://github.com/dhowe/Website/pull/73 fixed
