### ISSUE TITLE
Extra horizontal space for title in 4th column (only) of home page

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#72]
so that the 'architecture of association' title will not break onto 2 lines

![screen shot 2017-01-17 at 8 46 26 pm](https://cloud.githubusercontent.com/assets/737638/22021075/3d1d1016-dcf6-11e6-986d-6cf40a39987c.png)

**Comment by cqx931** [comment]
I have used a smaller font for title on homepage and an earlier break point to use 3 columns layout to solve this.
https://github.com/dhowe/Website/pull/73/commits/03bd1aef3371a6613837b4b41acb50f319b1d17b
