### ISSUE TITLE
Text looks strange on Firefox?

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#75]
perhaps just the big difference between italic and regular?

![screen shot 2017-01-18 at 8 31 59 pm](https://cloud.githubusercontent.com/assets/737638/22064150/40476378-ddbd-11e6-94e4-cfce5212122d.png)

**Comment by cqx931** [comment]
fixed now. https://github.com/dhowe/Website/pull/82/commits/88ce75e3429979e1339409f991a9b40ddc4d5644
