### ISSUE TITLE
AdverPos: Clicking on pages takes user to ad-detail view

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#77]
Zooming to detail should only happen when 

Recreate:
-- visit http://rednoise.org/daniel/adverpos/nicole.html
-- click anywhere on image

Or:
-- visit http://rednoise.org/daniel/adverpos/nicole.html
-- click to go to animation
-- click inside or outside of animation

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/Website/pull/82
