### ISSUE TITLE
Create separate column for years on pubs.html

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#79]
perhaps a bit wider than below:

![screen shot 2017-02-11 at 3 04 05 am](https://cloud.githubusercontent.com/assets/737638/22840038/ebe662b4-f006-11e6-8580-d1bcd61524a3.png)

**Comment by cqx931** [comment]
https://github.com/dhowe/Website/pull/80 Please check

**Comment by dhowe** [comment]
Looks great, but we should use a standard format for publications.json -- maybe bibjson, but let me do some quick research on what's best
