### ISSUE TITLE
Convert pubs to standard format

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#81]
First step is to grab each entry from google scholar as bibtex (and add to pubs.bib), then we can convert to js or json for rendering (I need to research the best js-compatible format/parser, maybe [this](https://github.com/pcooksey/bibtex-js))

For example, a bibtex entry:

```
@article{howe2015surveillance,
  title={Surveillance countermeasures: Expressive privacy via obfuscation},
  author={Howe, D},
  journal={APRJA, A Peer-Reviewed Journal About Datafied Research},
  volume={4},
  number={1},
  year={2015}
}
```

**Comment by dhowe** [comment]
see: https://github.com/pcooksey/bibtex-js/issues/8

**Comment by cqx931** [comment]
The following items can't be found on google scholar:

**Journal Articales**
“Generative Art and the Aesthetics of Surprise.” Howe, Daniel C. and Soderman, A. B. In Leonardo Electronic Almanac. Forthcoming 2017, Cambridge: MIT Press.

**Book Chapters**
“Protecting Sensitive Communication with Defensive Technology.” Howe, Daniel C. Chapter 25, in Boycott Classes, Continue Learning - A Review of the Theories and Thoughts Prior to the Umbrella Movement. Hong Kong: Step Forward Press, p239-251.

“Informed Consent in the Mozilla Browser: Implementing Value–Sensitive Design.” Friedman, B., Howe, D. C. and Felten, E. W. Chapter 9, in Internet Security: Hacking, CounterHacking, and Society, K. E. Himma (editor). Mass: Jones and Bartlett Publishers, p153–170.

“Values in Design: Theory and Practice.” Flanagan, M., Howe, D. C. and Nissenbaum, H. Chapter 16, in Information Technology and Moral Philosophy. Jeroen van den Hoven and John Weckert (eds.) Cambridge: Cambridge University Press, p322–353.

**Conference Proceedings**

“Making Humans Machine-readable: Obfuscation as Quantified Refusal". Howe, Daniel C. and Nissenbaum, H. Proceedings on Privacy Enhancing Technologies (PETS). Vol. 2017, No. 2. Submitted, June 2016. Under Review.

Proceedings of the 22nd International Symposium on Electronic Arts, Tapio-Leino, Howe, Charrieras et al. Editors. School of Creative Media, Hong Kong, May 2016.

“In Common Tongues.” Cayley, J. and Howe, Daniel C. In Remediating the Social. Bergen, Norway, University of Bergen, Department of Linguistic, Literary and Aesthetic Studies, p46–47.

**Other Publications**

Most of the items under "other publications can't be found with google scholar", except these two:

How It Is, in Common Tongues. Cayley, J. and Howe, Daniel C. Limited Edition Monograph, 297 pp., NLLF Press. ISBN–13: 978–0948454301

“Phantom Access Agent: a Client–Side Approach to Personal Information Control.”Zhao, X., Howe, D. C., Mazières, D. and Nissenbaum, H. New York University Report. Manuscript/Software.

**Comment by cqx931** [comment]
@dhowe

**Comment by dhowe** [comment]
You might use https://anystyle.io/ or similar. Shouldn't have to do it by hand...

**Comment by cqx931** [comment]
Please preview the publication page with bibtex in pubsBib.html
https://github.com/dhowe/Website/pull/91/commits/aaa34a29f1584772f7be391730f15decf3f11980

I didn't change the default template yet, do you have any specific style/template that you want to go for?

**Comment by cqx931** [comment]
I just updated the style and template for pubsBib.html. Please check: https://github.com/dhowe/Website/pull/183.

I have reviewed entries in pubs.bib up to year 2011 to match with the current publication page. I can continue this work tomorrow.
