### ISSUE TITLE
New page for website repo

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#83]
- [x] add http://rednoise.org/minordistance/tracks.html
- [x] modify it so it doesn't ~~use~~ require flash for the audio
- [x] look for other pages on rednoise linked from website but not in this repo (make list below)

**Comment by cqx931** [comment]
It is already not using flash, but jplayer (jquery HTML5 audio/video library) for the audio.

**Comment by cqx931** [comment]
**Projects with their own site**
[AdNauseam](https://adnauseam.io/)
[RiTa](http://rednoise.org/rita/)
[The Readers Project](http://thereadersproject.org/)
[How it is in Common Tongues](http://thereadersproject.org/hiiict2012.html#hiiict)
[The Real Story of Ah-Q](http://thereadersproject.org/installations/ahq.html)
[Read for Us](http://thereadersproject.org/installations/rfu.html#rfu)

**Project pages that are on rednoise but not in the website repo**
[AdLiPo](https://rednoise.org/adlipo/)
[Automatype](http://rednoise.org/~dhowe/automatype/)
[Engine of Engines](http://rednoise.org/eoe/)
[text.curtain](http://rednoise.org/daniel/textcurtain/)

**ELC Pages**
[Roulette](http://collection.eliterature.org/2/works/howe_roulette.html)
[open.ended](http://collection.eliterature.org/1/works/howe_kaprinska__open_ended.html)

**Comment by dhowe** [comment]
> It is already not using flash, but jplayer (jquery HTML5 audio/video library) for the audio.

When I access the page with chromium (no flash), I get a broken flash icon, and none of the audio will play. 

I also see the errors below in the console.

![screen shot 2017-02-22 at 11 36 47 am](https://cloud.githubusercontent.com/assets/737638/23196249/605f4698-f8f3-11e6-8a1c-6daa559736e1.png)
 
![screen shot 2017-02-22 at 11 37 10 am](https://cloud.githubusercontent.com/assets/737638/23196259/6b98e1e0-f8f3-11e6-8924-c76036bfe6e3.png)

**Comment by cqx931** [comment]
Interesting... I see something different from my console, I don't see the broken adobe icon and music is playing without flash enabled.
![image](https://cloud.githubusercontent.com/assets/3056154/23196666/07bef31e-f8f6-11e6-9e5d-cae53ffe8028.png)

**Comment by cqx931** [comment]
SoundManager should first try to use html5 to play the file. 
It seems to me that soundManager wrongly detected that your environment doesn't support playing mp3 files with HTML5. Therefore it is trying to use flash but failed.
![image](https://cloud.githubusercontent.com/assets/3056154/23198044/99364528-f8ff-11e6-8fd4-8f90e7c73bb9.png)

**Comment by cqx931** [comment]
This might be a bug in SoundManager(V2.97a.20130512), can you first try the[ latest version](http://www.schillmania.com/projects/soundmanager2/doc/download/) of SoundManager and see whether it fixes the problem you see?

**Comment by dhowe** [comment]
I still get a similar error (and the missing flash icon):

![image](https://cloud.githubusercontent.com/assets/737638/23205291/4b44dce2-f924-11e6-9c06-9ca72f564765.png)

**Comment by dhowe** [comment]
From the error above, seems mp3 is only enabled via flash -- perhaps convert to ogg?

**Comment by cqx931** [comment]
Can this be closed? Is the music playing on your computer?

**Comment by dhowe** [comment]
No. Still an error, a broken flash icon, and nothing playing in Chromium.

**Comment by cqx931** [comment]
This should work now...please check: https://github.com/dhowe/Website/pull/90
