### ISSUE TITLE
Migrate 4 pages to this repo

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#86]
- [x] [AdLiPo](https://rednoise.org/adlipo/)
- [x] [Automatype](http://rednoise.org/~dhowe/automatype/)
- [x] [Engine of Engines](http://rednoise.org/eoe/)
- [x] [text.curtain](http://rednoise.org/daniel/textcurtain/)

**Comment by cqx931** [comment]
Please check here: https://github.com/dhowe/Website/pull/89
