### ISSUE TITLE
Skechpad updates

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#9]
When nothing else is going on, please take a pass through the [json](https://github.com/dhowe/Website/blob/master/sketchpad/cells.json) for sketches in the sketchpad and do the following:

a) remove the entries with the following images:
- "img/sound_thumb.jpg" 
- "img/alg_thumb.jpg"
- "img/geomacles_thumb.jpg"
- "img/pub_thumb.jpg"
- "img/xflowers_thumb.jpg"
- "img/textkite_thumb.jpg"
- "img/singlestitch_thumb.jpg"
- "img/lineflock_thumb.jpg"

b) replace with these (pick a screenshot):

```
{
"url": "http://collection.eliterature.org/2/works/howe_roulette.html",
"description": "roulette is a work of recombinant narrative that offers a novel interactive reading experience..."
},
{
"url": "http://rednoise.org/sketches/Rectangles1/",
"description": "constraint-based sketch: only black/white rectangles with sin/cos"
},
{
"url": "http://rednoise.org/sketches/RasterWalk/",
"description": "recode of 'Random Walk Through Raster' by Frieder Nake for the ReCode project"
},
{
"url": "http://turbulence.org/project/no-time-machine/",
"description": "Quiet time, dead time, free time — call it what you will..."
},
{
"url": "http://rednoise.org/sketches/VoronoiRecode/",
"description": "recode of "Equidistant Space" by Peter Milojevic for the ReCode project"
},
{
"url": "http://rednoise.org/glyphflock/",
"description": "demo extracting points from a font path with p5.js"
},
{
"url": "./noisetree.pde",
"description": "recursive tree animated with noise"
},
{
"url": "http://rednoise.org/eoe/",
"description": "engine of engines, with bill seaman, is a reactive networked installation... "
}


// note 1: code for no-time-machine is here: http://rednoise.org/notime/
// note 2: noisetree also has a p5js version in the same place but the oline() function has issues

```

c)  note note any broken links, and any java that we might be able to replace with p5js. 

d)  copy any remote sketches into the repository and then update the links to be relative (can also remove 'smallwin' from the json entries as its in every entry (but check that it doesn't break anything in the code))

**Comment by cqx931** [comment]
the link of the rapunsel project is broken, when I do a search I can only find related papers. Please let me know which link you would like to replace with or shall I delete this one?
http://www.rapunsel.org/

**Comment by cqx931** [comment]
http://collection.eliterature.org/2/works/howe_roulette.html
Roulette is downloadable and it is in java. Are we going to port it to p5js and add the sketch to sketchpad later?

**Comment by cqx931** [comment]
https://github.com/dhowe/Website/pulls
a) All listed items removed both in images folder as well as in cells.json
b)All items added to sketchpad with thumb images.
https://github.com/dhowe/Website/pull/11/commits/4fd676cceb4bcadf23a9e0f6e0bdf64c89154983
d) removed smallwin from json, sketchpad works fine.

**Comment by cqx931** [comment]
close
