### ISSUE TITLE
Confusing zoom interface

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#92]
When zooming in on the ad sets, the cursor changes to a plus sign, which implies that a click will zoom in, which it doesn't. So we either need to make clicks zoom in, in addition to the mouse-wheel OR some kind of popup/hover message on click that tells the user to use the mouse-wheel...

![screen shot 2017-03-26 at 12 53 42 am](https://cloud.githubusercontent.com/assets/737638/24324294/ad4291fc-11be-11e7-9977-cbb69a26bfec.png)

**Comment by dhowe** [comment]
@cqx931 status?

**Comment by cqx931** [comment]
Please check: 
https://github.com/cqx931/Website/commit/29e29aa707394b88d18a6b03bf12b3d91395abfb

1.Change the plus sign cursor back to click
2.Showing hint "Zoom with mouse wheel or touch pad" after click.

**Comment by cqx931** [comment]
Can this be closed?
