### ISSUE TITLE
Updated ChinaEye image with new interface

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#95]
can perhaps use this one: 

> https://lh3.googleusercontent.com/oY33QfoJf4g_Yz7JvX19HSokv3cPah-2EcZbGZWVmhOdoCUMWIhRHUcPE2iRGM08G4V0O9WL=s640-h400-e365-rw

also add link to chrome-store when live (check this url): https://chrome.google.com/webstore/detail/chinaeye/kbkejkbhaiggcfnalkdlphlikillhlpf
<hr>

![image](https://cloud.githubusercontent.com/assets/737638/25086291/5d3a74e4-2399-11e7-9795-2338653cef53.png)

**Comment by cqx931** [comment]
https://github.com/dhowe/Website/commit/012a42953069f41845790e09020a095844a4e5a0
