### ISSUE TITLE
New projects for website

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#98]
Need text/images for these projects in various state of finished-ness. Once we discuss, you should take a first pass at text/images, then I will make edits and give feedback. Note that until approved, these should not be linked from the index page

~**All your Google are belong to us**  (see #118)~

**ProxyPal** (on hold)

**No Time Machine**

~**Perceptual Reader**~ done

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/Website/pull/119
